{pkgs, ...}: {
  home-manager.sharedModules = [
    (_: {
      home.packages = with pkgs; [
        micro
      ];

      xdg.desktopEntries.micro = {
        name = "Micro Editor";
        genericName = "Text Editor";
        exec = "kitty -e micro %F";
        icon = "text-editor";
        terminal = false;
        categories = ["Utility" "TextEditor"];
        mimeType = ["text/plain" "text/x-readme" "text/markdown" "application/x-shellscript" "text/x-csrc" "text/x-chdr" "text/x-c++src" "text/x-c++hdr" "text/x-java" "text/x-python" "text/x-script.python" "application/json" "application/xml" "text/xml" "text/x-yaml" "text/x-toml" "text/css" "text/javascript" "application/javascript" "text/x-lua" "text/x-makefile" "text/x-nix"];
      };

      xdg.mimeApps = {
        enable = true;
        defaultApplications = {
          "text/plain" = "micro.desktop";
        };
      };

      xdg.configFile."micro/settings.json".text = builtins.toJSON {
        # `dankcolors` is generated by the DMS matugen pipeline below.
        colorscheme = "dankcolors";
        autosu = true;
        mkparents = true;
        scrollbar = true;
        scrollmargin = 3;
        scrollspeed = 2;
        tabsize = 2;
        tabstospaces = true;
        ruler = true;
        colorcolumn = 80;
        cursorline = true;
        infobar = true;
        diff = true;
        saveundo = false; # Disabled due to version upgrade issues
      };

      # Matugen template for micro's colorscheme format. Each entry is
      # `color-link <element> "<fg>,<bg>"` (truecolor) or `"<fg>"` for
      # fg-only. Mapping mirrors the btop module: primary/tertiary/dank16
      # for syntax categories so micro stays visually consistent with the
      # rest of the matugen-driven UI.
      xdg.configFile."matugen/dms/templates/micro.micro".text = ''
        color-link default "{{colors.on_surface.default.hex}},{{colors.surface.default.hex}}"
        color-link comment "{{colors.on_surface_variant.default.hex}}"
        color-link identifier "{{dank16.color4.default.hex}}"
        color-link identifier.class "{{dank16.color6.default.hex}}"
        color-link constant "{{dank16.color3.default.hex}}"
        color-link constant.string "{{dank16.color2.default.hex}}"
        color-link constant.string.char "{{dank16.color2.default.hex}}"
        color-link constant.number "{{dank16.color3.default.hex}}"
        color-link constant.bool "{{dank16.color3.default.hex}}"
        color-link statement "{{dank16.color5.default.hex}}"
        color-link preproc "{{dank16.color1.default.hex}}"
        color-link type "{{dank16.color6.default.hex}}"
        color-link special "{{dank16.color5.default.hex}}"
        color-link symbol "{{colors.on_surface.default.hex}}"
        color-link symbol.brackets "{{colors.on_surface.default.hex}}"
        color-link symbol.tag "{{dank16.color4.default.hex}}"
        color-link gutter-error "{{dank16.color1.default.hex}}"
        color-link gutter-warning "{{dank16.color3.default.hex}}"
        color-link status "{{colors.on_primary.default.hex}},{{colors.primary.default.hex}}"
        color-link statusline "{{colors.on_primary.default.hex}},{{colors.primary.default.hex}}"
        color-link tabbar "{{colors.on_surface.default.hex}},{{colors.surface_container.default.hex}}"
        color-link indent-char "{{colors.outline_variant.default.hex}}"
        color-link line-number "{{colors.on_surface_variant.default.hex}},{{colors.surface.default.hex}}"
        color-link current-line-number "{{colors.primary.default.hex}},{{colors.surface.default.hex}}"
        color-link cursor-line "{{colors.on_surface.default.hex}},{{colors.surface_container.default.hex}}"
        color-link color-column "{{colors.surface_container.default.hex}}"
        color-link selection "{{colors.on_primary_container.default.hex}},{{colors.primary_container.default.hex}}"
        color-link match-brace "{{colors.on_primary.default.hex}},{{colors.primary.default.hex}}"
        color-link hlsearch "{{colors.on_tertiary.default.hex}},{{colors.tertiary.default.hex}}"
        color-link todo "{{dank16.color3.default.hex}}"
        color-link error "{{colors.on_error.default.hex}},{{colors.error.default.hex}}"
        color-link diff-added "{{dank16.color2.default.hex}}"
        color-link diff-modified "{{dank16.color3.default.hex}}"
        color-link diff-deleted "{{dank16.color1.default.hex}}"
      '';
      xdg.configFile."matugen/dms/configs/micro.toml".text = ''
        [templates.micro]
        input_path = '~/.config/matugen/dms/templates/micro.micro'
        output_path = '~/.config/micro/colorschemes/dankcolors.micro'
      '';

      # Set environment variable for true color support
      home.sessionVariables = {
        MICRO_TRUECOLOR = "1";
      };
    })
  ];
}
