{...}: {
  home-manager.sharedModules = [
    (_: {
      programs.btop = {
        enable = true;
        settings = {
          # Theme is generated by DMS's matugen pipeline (see the template
          # + drop-in config below). DMS regenerates this file on every
          # wallpaper change AND every dark/light toggle (because
          # `syncModeWithPortal = true` in dms/settings.json), so the
          # palette tracks whatever the rest of the system is doing.
          color_theme = "dankcolors";

          # Drop btop's own background fill so the terminal's bg shows
          # through. The terminal palette is also DMS-driven (kitty +
          # ghostty matugen templates), so leaving the background to the
          # terminal is what actually makes btop *visually* follow
          # light/dark — a light-mode palette with btop's old hard-coded
          # `#1E1E2E` underneath would still look like a dark-mode app.
          #
          # Caveat the UI cannot fix: btop reads its theme exactly once,
          # at startup. A running btop instance keeps the colours it
          # loaded; restart btop (or just relaunch the systemd-monitor
          # tab) after toggling dark/light to pick up the new theme.
          theme_background = false;
        };
      };

      # Matugen template for btop. Variables resolve against DMS's full
      # palette: every `colors.X` and `dank16.colorN` exposes `.default`
      # (the active variant per the portal's color-scheme), `.dark`, and
      # `.light`. Using `.default` everywhere is what makes the theme
      # follow the system mode toggle — `terminalsAlwaysDark` only
      # rewrites `.default` → `.dark` for DMS's *built-in* terminal
      # templates (kitty/ghostty/foot/...), not for user templates like
      # this one, so we don't accidentally inherit that override.
      #
      # Box outlines (cpu/mem/net/proc) and graph gradients are pulled
      # from the dank16 ANSI palette so each box keeps a distinct hue
      # that mirrors the terminal's own 16-colour palette.
      xdg.configFile."matugen/dms/templates/btop.theme".text = ''
        # Empty bg + theme_background=false in btop.conf = transparent.
        theme[main_bg]=""

        theme[main_fg]="{{colors.on_surface.default.hex}}"
        theme[title]="{{colors.on_surface.default.hex}}"
        theme[hi_fg]="{{colors.primary.default.hex}}"
        theme[selected_bg]="{{colors.primary_container.default.hex}}"
        theme[selected_fg]="{{colors.on_primary_container.default.hex}}"
        theme[inactive_fg]="{{colors.on_surface_variant.default.hex}}"
        theme[graph_text]="{{colors.on_surface.default.hex}}"
        theme[meter_bg]="{{colors.surface_variant.default.hex}}"
        theme[proc_misc]="{{colors.tertiary.default.hex}}"

        # CPU / Memory / Network / Process box outlines.
        theme[cpu_box]="{{dank16.color5.default.hex}}"
        theme[mem_box]="{{dank16.color2.default.hex}}"
        theme[net_box]="{{dank16.color1.default.hex}}"
        theme[proc_box]="{{dank16.color4.default.hex}}"

        theme[div_line]="{{colors.outline_variant.default.hex}}"

        # Temperature gradient: green -> yellow -> red.
        theme[temp_start]="{{dank16.color2.default.hex}}"
        theme[temp_mid]="{{dank16.color3.default.hex}}"
        theme[temp_end]="{{dank16.color1.default.hex}}"

        # CPU usage gradient: blue -> cyan -> magenta.
        theme[cpu_start]="{{dank16.color4.default.hex}}"
        theme[cpu_mid]="{{dank16.color6.default.hex}}"
        theme[cpu_end]="{{dank16.color5.default.hex}}"

        # Mem/Disk free meter: bright blue -> blue -> bright magenta.
        theme[free_start]="{{dank16.color12.default.hex}}"
        theme[free_mid]="{{dank16.color4.default.hex}}"
        theme[free_end]="{{dank16.color13.default.hex}}"

        # Mem/Disk cached meter: bright cyan -> cyan -> bright blue.
        theme[cached_start]="{{dank16.color14.default.hex}}"
        theme[cached_mid]="{{dank16.color6.default.hex}}"
        theme[cached_end]="{{dank16.color12.default.hex}}"

        # Mem/Disk available meter: yellow -> bright red -> red.
        theme[available_start]="{{dank16.color3.default.hex}}"
        theme[available_mid]="{{dank16.color9.default.hex}}"
        theme[available_end]="{{dank16.color1.default.hex}}"

        # Mem/Disk used meter: green -> bright green -> cyan.
        theme[used_start]="{{dank16.color2.default.hex}}"
        theme[used_mid]="{{dank16.color10.default.hex}}"
        theme[used_end]="{{dank16.color6.default.hex}}"

        # Network download: yellow -> bright red -> red.
        theme[download_start]="{{dank16.color3.default.hex}}"
        theme[download_mid]="{{dank16.color9.default.hex}}"
        theme[download_end]="{{dank16.color1.default.hex}}"

        # Network upload: green -> bright green -> cyan.
        theme[upload_start]="{{dank16.color2.default.hex}}"
        theme[upload_mid]="{{dank16.color10.default.hex}}"
        theme[upload_end]="{{dank16.color6.default.hex}}"

        # Process box gradient: cyan -> blue -> magenta.
        theme[process_start]="{{dank16.color6.default.hex}}"
        theme[process_mid]="{{dank16.color4.default.hex}}"
        theme[process_end]="{{dank16.color5.default.hex}}"
      '';

      # Per-app matugen drop-in. DMS's matugen-workers.sh scans
      # ~/.config/matugen/dms/configs/*.toml on every theme refresh and
      # runs each listed template in addition to its built-in ones.
      # Using this drop-in directory rather than the global
      # ~/.config/matugen/config.toml keeps each app self-contained, so
      # adding a future matugen-driven app (say, neovim) only means
      # dropping another tiny .toml + template alongside this one
      # instead of editing a shared file.
      xdg.configFile."matugen/dms/configs/btop.toml".text = ''
        [templates.btop]
        input_path = '~/.config/matugen/dms/templates/btop.theme'
        output_path = '~/.config/btop/themes/dankcolors.theme'
      '';
    })
  ];
}
