{
  lib,
  pkgs,
  inputs,
  browser,
  editor,
  terminal,
  terminalFileManager,
  kbdLayout,
  kbdVariant,
  ...
}: {
  imports = [
    ../../themes/Catppuccin # Catppuccin GTK and QT themes
    ./programs/noctalia # bar, launcher, notifs, lock, OSD, session, clipboard, wallpaper
    ./programs/hypridle # idle timeouts; drives noctalia lock
  ];

  nix.settings = {
    substituters = ["https://hyprland.cachix.org"];
    trusted-public-keys = ["hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="];
  };

  systemd.user.services.hyprpolkitagent = {
    description = "Hyprpolkitagent - Polkit authentication agent";
    wantedBy = ["graphical-session.target"];
    wants = ["graphical-session.target"];
    after = ["graphical-session.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.hyprpolkitagent}/libexec/hyprpolkitagent";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };
  services.displayManager.defaultSession = "hyprland";

  programs.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
    # withUWSM = true;
  };

  home-manager.sharedModules = let
    inherit (lib) getExe getExe';
    autoclicker = pkgs.callPackage ./scripts/autoclicker.nix {};
    varsLua = ''
      -- Auto-generated by modules/desktop/hyprland/default.nix.
      -- DO NOT EDIT BY HAND. Edit the Nix expression instead.
      return {
        term        = "${getExe pkgs.${terminal}}",
        editor      = "${editor}",
        browser     = "${browser}",
        fileManager = "${getExe pkgs.${terminal}} --class terminalFileManager -e ${terminalFileManager}",
        kbdLayout   = "${kbdLayout},is",
        kbdVariant  = "${kbdVariant},",

        scripts = {
          keybinds        = "${./scripts/keybinds.sh}",
          dontkillsteam   = "${./scripts/dontkillsteam.sh}",
          keyboardswitch  = "${./scripts/keyboardswitch.sh}",
          gamemode        = "${./scripts/gamemode.sh}",
          rebuild         = "${./scripts/rebuild.sh}",
          restartNoctalia = "${./scripts/restart-noctalia.sh}",
        },

        bin = {
          hyprsunset  = "${getExe pkgs.hyprsunset}",
          btop        = "${getExe pkgs.btop}",
          wlPaste     = "${getExe' pkgs.wl-clipboard "wl-paste"}",
          autoclicker = "${getExe autoclicker}",
        },
      }
    '';
  in [
    ({...}: {
      home.packages = with pkgs; [
        # Noctalia replaces: waybar, hyprpaper, cliphist, grimblast, swappy
        # (most are now built into the shell). Kept utilities still used by
        # other binds / system integration:
        hyprpicker
        hyprshot # SUPER+P screenshot region capture
        hyprland-qtutils
        libnotify
        brightnessctl
        pamixer
        pavucontrol
        playerctl
        wtype
        wl-clipboard
        xdotool
        yad
      ];

      # Hyprland 0.55+ Lua config. Hyprland picks Lua over hyprlang at startup
      # whenever hyprland.lua is present, so home-manager's `settings`/`extraConfig`
      # output (hyprland.conf) is now ignored. To recover from a Lua-side breakage,
      # rename or delete this file and Hyprland transparently falls back to the
      # still-present hyprland.conf.
      xdg.configFile."hypr/hyprland.lua".source = ./lua/hyprland.lua;
      xdg.configFile."hypr/vars.lua".text = varsLua;
      xdg.configFile."hypr/monitors.lua".source = ./lua/monitors.lua;
      xdg.configFile."hypr/env.lua".source = ./lua/env.lua;
      xdg.configFile."hypr/misc.lua".source = ./lua/misc.lua;
      xdg.configFile."hypr/looknfeel.lua".source = ./lua/looknfeel.lua;
      xdg.configFile."hypr/input.lua".source = ./lua/input.lua;
      xdg.configFile."hypr/autostart.lua".source = ./lua/autostart.lua;
      xdg.configFile."hypr/rules.lua".source = ./lua/rules.lua;
      xdg.configFile."hypr/binds.lua".source = ./lua/binds.lua;

      #test later systemd.user.targets.hyprland-session.Unit.Wants = [ "xdg-desktop-autostart.target" ];
      wayland.windowManager.hyprland = {
        enable = true;
        package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
        portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
        plugins = [
          # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprwinwrap
        ];
        systemd = {
          enable = true;
          variables = ["--all"];
        };
        # Hyprland loads hypr/hyprland.lua when present; HM only needs non-empty
        # extraConfig here to avoid the "systemd/plugins but no settings" warning.
        extraConfig = "# primary config: hyprland.lua (xdg.configFile)";
        settings = {};
      };
    })
  ];
}
