{
  lib,
  pkgs,
  browser,
  editor,
  terminal,
  terminalFileManager,
  kbdLayout,
  kbdVariant,
  ...
}: {
  imports = [
    # GTK/Qt/icon/cursor + dark-light mode are managed dynamically by DMS
    # (matugen templates + syncModeWithPortal). No static theme module is
    # imported here on purpose — adding one re-applies its color-scheme
    # and gtk-application-prefer-dark-theme keys on every rebuild and
    # overrides whatever the user picked in DMS Settings.
    ./programs/dms # DankMaterialShell: bar, launcher, notifs, lock, OSD, session, clipboard, wallpaper
    ./programs/hypridle # idle timeouts; drives DMS lock screen
  ];

  systemd.user.services.hyprpolkitagent = {
    description = "Hyprpolkitagent - Polkit authentication agent";
    wantedBy = ["graphical-session.target"];
    wants = ["graphical-session.target"];
    after = ["graphical-session.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.hyprpolkitagent}/libexec/hyprpolkitagent";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };
  services.displayManager.defaultSession = "hyprland";

  programs.hyprland = {
    enable = true;
    # withUWSM = true;
  };

  home-manager.sharedModules = let
    inherit (lib) getExe getExe';
    autoclicker = pkgs.callPackage ./scripts/autoclicker.nix {};
    varsLua = ''
      -- Auto-generated by modules/desktop/hyprland/default.nix.
      -- DO NOT EDIT BY HAND. Edit the Nix expression instead.
      return {
        term        = "${getExe pkgs.${terminal}}",
        editor      = "${editor}",
        browser     = "${browser}",
        fileManager = "${getExe pkgs.${terminal}} --class=terminalFileManager -e ${terminalFileManager}",
        kbdLayout   = "${kbdLayout},is",
        kbdVariant  = "${kbdVariant},",

        scripts = {
          dontkillsteam   = "${./scripts/dontkillsteam.sh}",
          keyboardswitch  = "${./scripts/keyboardswitch.sh}",
          rebuild         = "${./scripts/rebuild.sh}",
          restartDms      = "${./scripts/restart-dms.sh}",
          screenshot      = "${./scripts/screenshot.sh}",
          tlpCycle        = "${./scripts/tlp-cycle.sh}",
        },

        bin = {
          hyprsunset  = "${getExe pkgs.hyprsunset}",
          btop        = "${getExe pkgs.btop}",
          wlPaste     = "${getExe' pkgs.wl-clipboard "wl-paste"}",
          autoclicker = "${getExe autoclicker}",
        },
      }
    '';
  in [
    ({...}: {
      home.packages = with pkgs; [
        # DMS replaces: waybar, hyprpaper, grimblast, hyprshot, copyq
        # (bar, wallpaper, lock, notifications, OSD, control center, and
        # built-in clipboard manager are all part of the shell). Kept
        # utilities still used by other keybinds / system integration:
        hyprpicker
        hyprland-qtutils
        libnotify # notify-send (used by scripts/tlp-cycle.sh fallback)
        brightnessctl
        pamixer
        pavucontrol
        playerctl
        wl-clipboard # wl-copy (used by scripts/screenshot.sh)
        xdotool

        # Runtime backend for DMS's built-in clipboard manager (bound
        # to SUPER+V via `dms ipc call clipboard toggle`). cliphist
        # stores wl-paste's clipboard stream to a local DB; DMS reads
        # from / writes to that DB via the cliphist CLI. The actual
        # capture daemon is started from lua/autostart.lua.
        cliphist

        # Runtime deps for the screenshot keybind (SUPER+P → scripts/
        # screenshot.sh). DMS only ships an `ipc niri screenshot` IPC
        # for the niri compositor; on Hyprland we drive grim+slurp+satty
        # ourselves. They have to be on $PATH for the graphical session.
        #   grim         region screenshot capture (Wayland)
        #   slurp        interactive region selector
        #   satty        image markup editor
        #   wf-recorder  screen recording backend (used ad-hoc; not
        #                wired into a keybind today)
        #   xdg-utils    xdg-open (used by various other apps)
        grim
        slurp
        satty
        wf-recorder
        xdg-utils
      ];

      # Hyprland 0.55+ Lua config. Hyprland picks Lua over hyprlang at startup
      # whenever hyprland.lua is present, so home-manager's `settings`/`extraConfig`
      # output (hyprland.conf) is now ignored. To recover from a Lua-side breakage,
      # rename or delete this file and Hyprland transparently falls back to the
      # still-present hyprland.conf.
      xdg.configFile."hypr/hyprland.lua".source = ./lua/hyprland.lua;
      xdg.configFile."hypr/vars.lua".text = varsLua;
      xdg.configFile."hypr/monitors.lua".source = ./lua/monitors.lua;
      xdg.configFile."hypr/env.lua".source = ./lua/env.lua;
      xdg.configFile."hypr/misc.lua".source = ./lua/misc.lua;
      xdg.configFile."hypr/looknfeel.lua".source = ./lua/looknfeel.lua;
      xdg.configFile."hypr/input.lua".source = ./lua/input.lua;
      xdg.configFile."hypr/autostart.lua".source = ./lua/autostart.lua;
      xdg.configFile."hypr/rules.lua".source = ./lua/rules.lua;
      xdg.configFile."hypr/binds.lua".source = ./lua/binds.lua;

      #test later systemd.user.targets.hyprland-session.Unit.Wants = [ "xdg-desktop-autostart.target" ];
      wayland.windowManager.hyprland = {
        enable = true;
        plugins = [];
        systemd = {
          enable = true;
          variables = ["--all"];
        };
        # Hyprland loads hypr/hyprland.lua when present; HM only needs non-empty
        # extraConfig here to avoid the "systemd/plugins but no settings" warning.
        extraConfig = "# primary config: hyprland.lua (xdg.configFile)";
        settings = {};
      };
    })
  ];
}
