{
  lib,
  pkgs,
  inputs,
  browser,
  editor,
  terminal,
  terminalFileManager,
  kbdLayout,
  kbdVariant,
  ...
}: {
  imports = [
    ../../themes/Catppuccin # Catppuccin GTK and QT themes
    ./programs/waybar
    ./programs/wlogout
    ./programs/rofi
    ./programs/hypridle
    ./programs/hyprlock
    ./programs/swaync
  ];

  nix.settings = {
    substituters = ["https://hyprland.cachix.org"];
    trusted-public-keys = ["hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="];
  };

  systemd.user.services.hyprpolkitagent = {
    description = "Hyprpolkitagent - Polkit authentication agent";
    wantedBy = ["graphical-session.target"];
    wants = ["graphical-session.target"];
    after = ["graphical-session.target"];
    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.hyprpolkitagent}/libexec/hyprpolkitagent";
      Restart = "on-failure";
      RestartSec = 1;
      TimeoutStopSec = 10;
    };
  };
  services.displayManager.defaultSession = "hyprland";

  programs.hyprland = {
    enable = true;
    package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
    # withUWSM = true;
  };

  home-manager.sharedModules = let
    inherit (lib) getExe getExe';
    autoclicker = pkgs.callPackage ./scripts/autoclicker.nix {};
    varsLua = ''
      -- Auto-generated by modules/desktop/hyprland/default.nix.
      -- DO NOT EDIT BY HAND. Edit the Nix expression instead.
      return {
        term        = "${getExe pkgs.${terminal}}",
        editor      = "${editor}",
        browser     = "${browser}",
        fileManager = "${getExe pkgs.${terminal}} --class terminalFileManager -e ${terminalFileManager}",
        kbdLayout   = "${kbdLayout},is",
        kbdVariant  = "${kbdVariant},",

        scripts = {
          keybinds       = "${./scripts/keybinds.sh}",
          dontkillsteam  = "${./scripts/dontkillsteam.sh}",
          rofi           = "${./scripts/rofi.sh}",
          keyboardswitch = "${./scripts/keyboardswitch.sh}",
          gamemode       = "${./scripts/gamemode.sh}",
          clipManager    = "${./scripts/ClipManager.sh}",
          rofimusic      = "${./scripts/rofimusic.sh}",
          screenshot     = "${./scripts/screenshot.sh}",
          rebuild        = "${./scripts/rebuild.sh}",
          batterynotify  = "${./scripts/batterynotify.sh}",
        },

        bin = {
          hyprsunset  = "${getExe pkgs.hyprsunset}",
          btop        = "${getExe pkgs.btop}",
          wlPaste     = "${getExe' pkgs.wl-clipboard "wl-paste"}",
          autoclicker = "${getExe autoclicker}",
        },
      }
    '';
  in [
    ({...}: {
      home.packages = with pkgs; [
        hyprpaper
        hyprpicker
        hyprland-qtutils
        cliphist
        grimblast
        swappy
        libnotify
        brightnessctl
        networkmanagerapplet
        networkmanager_dmenu
        pamixer
        pavucontrol
        playerctl
        waybar
        wtype
        wl-clipboard
        xdotool
        yad
        # socat # for and autowaybar.sh
        # jq # for and autowaybar.sh
      ];

      xdg.configFile."hypr/icons" = {
        source = ./icons;
        recursive = true;
      };

      # Hyprland 0.55+ Lua config. Hyprland picks Lua over hyprlang at startup
      # whenever hyprland.lua is present, so home-manager's `settings`/`extraConfig`
      # output (hyprland.conf) is now ignored. To recover from a Lua-side breakage,
      # rename or delete this file and Hyprland transparently falls back to the
      # still-present hyprland.conf.
      xdg.configFile."hypr/hyprland.lua".source = ./lua/hyprland.lua;
      xdg.configFile."hypr/vars.lua".text = varsLua;
      xdg.configFile."hypr/monitors.lua".source = ./lua/monitors.lua;
      xdg.configFile."hypr/env.lua".source = ./lua/env.lua;
      xdg.configFile."hypr/misc.lua".source = ./lua/misc.lua;
      xdg.configFile."hypr/looknfeel.lua".source = ./lua/looknfeel.lua;
      xdg.configFile."hypr/input.lua".source = ./lua/input.lua;
      xdg.configFile."hypr/autostart.lua".source = ./lua/autostart.lua;
      xdg.configFile."hypr/rules.lua".source = ./lua/rules.lua;
      xdg.configFile."hypr/binds.lua".source = ./lua/binds.lua;

      #test later systemd.user.targets.hyprland-session.Unit.Wants = [ "xdg-desktop-autostart.target" ];
      wayland.windowManager.hyprland = {
        enable = true;
        package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
        portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
        plugins = [
          # inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprwinwrap
        ];
        systemd = {
          enable = true;
          variables = ["--all"];
        };
        settings = {};
      };
    })
  ];
}
