-- Hyprland 0.55+ Lua configuration entry point.
--
-- This file is loaded by Hyprland at startup whenever it is present at
-- $XDG_CONFIG_HOME/hypr/hyprland.lua. Each section lives in its own partial
-- under the same directory; vars.lua is generated by Nix and exposes script
-- paths, terminal/browser/editor commands and the kbd layout.

require("monitors")
require("env")
require("looknfeel")
require("misc")
require("input")
require("rules")
require("autostart")
require("binds")
